import PhoningSessionNumberFoundOtherDeviceScreen from "@/screens/phoningSessionNumberFoundOtherDevice/PhoningSessionNumberFoundOtherDeviceScreen";
export default PhoningSessionNumberFoundOtherDeviceScreen;
