import PhoningSessionLoaderPermanentCampaignScreen from "@/screens/phoningSessionLoaderPermanentCampaign/PhoningSessionLoaderPermanentCampaignScreen";
export default PhoningSessionLoaderPermanentCampaignScreen;
