export default {
'PublicSans-Black': require('assets/fonts/PublicSans/PublicSans-Black.ttf'),
'PublicSans-BlackItalic': require('assets/fonts/PublicSans/PublicSans-BlackItalic.ttf'),
'PublicSans-Bold': require('assets/fonts/PublicSans/PublicSans-Bold.ttf'),
'PublicSans-BoldItalic': require('assets/fonts/PublicSans/PublicSans-BoldItalic.ttf'),
'PublicSans-ExtraBold': require('assets/fonts/PublicSans/PublicSans-ExtraBold.ttf'),
'PublicSans-ExtraBoldItalic': require('assets/fonts/PublicSans/PublicSans-ExtraBoldItalic.ttf'),
'PublicSans-ExtraLight': require('assets/fonts/PublicSans/PublicSans-ExtraLight.ttf'),
'PublicSans-ExtraLightItalic': require('assets/fonts/PublicSans/PublicSans-ExtraLightItalic.ttf'),
'PublicSans-Italic': require('assets/fonts/PublicSans/PublicSans-Italic.ttf'),
'PublicSans-Light': require('assets/fonts/PublicSans/PublicSans-Light.ttf'),
'PublicSans-LightItalic': require('assets/fonts/PublicSans/PublicSans-LightItalic.ttf'),
'PublicSans-Medium': require('assets/fonts/PublicSans/PublicSans-Medium.ttf'),
'PublicSans-MediumItalic': require('assets/fonts/PublicSans/PublicSans-MediumItalic.ttf'),
'PublicSans-Regular': require('assets/fonts/PublicSans/PublicSans-Regular.ttf'),
'PublicSans-SemiBold': require('assets/fonts/PublicSans/PublicSans-SemiBold.ttf'),
'PublicSans-SemiBoldItalic': require('assets/fonts/PublicSans/PublicSans-SemiBoldItalic.ttf'),
'PublicSans-Thin': require('assets/fonts/PublicSans/PublicSans-Thin.ttf'),
'PublicSans-ThinItalic': require('assets/fonts/PublicSans/PublicSans-ThinItalic.ttf'),
'SharpGrotesk-SemiBold25': require('assets/fonts/SharpGrotesk-SemiBold25.ttf'),
'Value-Bold': require('assets/fonts/Value-Bold.ttf'),
'Value-Medium': require('assets/fonts/Value-Medium.ttf'),
'Value-MediumItalic': require('assets/fonts/Value-MediumItalic.ttf'),
'Value-Regular': require('assets/fonts/Value-Regular.ttf'),
} as const;