export class CredentialsInvalidError extends Error {}
export class ServerTimeoutError extends Error {}
export class BadRequestError extends Error {}
export class UnauthorizedError extends Error {}
export class ForbiddenError extends Error {}
export class NotFoundError extends Error {}
export class InternalServerError extends Error {}
export class RefreshTokenPermanentlyInvalidatedError extends Error {}
export class DepartmentNotFoundError extends Error {}
