export const API_BASE_URL = '{{{RN_API_BASE_URL}}}'
export const OAUTH_CLIENT_ID = '{{{RN_CLIENT_ID}}}'
export const OAUTH_CLIENT_SECRET = '{{{RN_CLIENT_SECRET}}}'
export const ENVIRONMENT = '{{{RN_ENVIRONMENT}}}'
export const SENTRY_DSN = '{{{RN_SENTRY_DSN}}}'
export const GOOGLE_PLACES_API_KEY = '{{{RN_GOOGLE_PLACES_API_KEY}}}'
export const BUNDLE_ID = '{{{RN_BUNDLE_ID}}}'
