export const API_BASE_URL = '{{{RN_API_BASE_URL}}}'
export const OAUTH_CLIENT_ID = '{{{RN_CLIENT_ID}}}'
export const OAUTH_CLIENT_SECRET = '{{{RN_CLIENT_SECRET}}}'
export const ENVIRONMENT = '{{{RN_ENVIRONMENT}}}'
export const SENTRY_DSN = '{{{RN_SENTRY_DSN}}}'
