export const white = '#ffffff'
const springWood = '#f9f6f4'
const springWood10Dark = '#fcfbfa'

export const shipGray = '#413d45'
const ebony = '#10152F'
const boulder = '#767676'
const cararra = '#eae8e4'
const cinnarbar = '#e74536'
const lightGrey = '#e7e9ec'
const doveGray = '#6a6a6a'
const iceBlue = '#f5faff'
const anakiwa = '#b1d8ff'
const shakespeare = '#5BAEDB'
const shakespeare70Light = '#cee6f4'
const shakespeare50Light = '#add6ed'
const anakiwa2 = '#B1D8FF'
const monza = '#CC0613'
const portGore = '#1D214F'
const comet = '#616481'
const pickledBluewood = '#383b64'

export const darkText = ebony
export const lightText = boulder
export const veryLightText = white
export const lightTextOnLightBackground = doveGray
export const tagBackground = anakiwa2
export const defaultBackground = white
export const touchHighlight = '#dddddd'
export const navigationBackground = white
export const navigationTint = shakespeare
export const secondaryButtonText = shipGray
export const secondaryButtonBackground = springWood
export const secondaryButtonDisabled = springWood10Dark
export const tertiaryButtonBackground = white
export const progressBackground = cararra
export const inputTextBorder = '#eaeaea'
export const loadingOverlayBackground = '#00000033'
export const inputTextErrorMessage = cinnarbar
export const modalOverlayBackground = '#00000066'
export const groupedListBackground = springWood
export const separator = lightGrey
export const activeItemBackground = springWood
export const primaryColor = shakespeare
export const accent = monza
export const tabBarBackground = portGore
export const tabBarActiveTint = white
export const tabBarInactiveTint = comet
export const tabBarRipple = pickledBluewood
export const lightBackground = iceBlue
export const primaryButtonBackgroundDisabled = shakespeare70Light
export const primaryButtonBackgroundHighlight = shakespeare50Light
export const primaryButtonTextColor = white
export const coloredText = shakespeare
export const quickPollProgress = anakiwa
export const actionCardBackground = portGore
export const actionCardHighlight = pickledBluewood
