export const white = '#ffffff'
const springWood = '#f9f6f4'
const springWood10Dark = '#fcfbfa'
export const shipGray = '#413d45'
const spunPearl = '#a9a5ae'
const cararra = '#eae8e4'
const cinnarbar = '#e74536'
const lightGrey = '#e7e9ec'
const doveGray = '#6a6a6a'
const blueRibbon = '#0d65ff'
const blueRibbon80Light = '#4387ff'
const blueRibbon50Light = '#86b2ff'
const iceBlue = '#f5faff'
const anakiwa = '#b1d8ff'

export const tab = doveGray
export const darkText = shipGray
export const lightText = spunPearl
export const veryLightText = white
export const lightTextOnLightBackground = doveGray
export const tagBackground = shipGray
export const defaultBackground = white
export const touchHighlight = '#dddddd'
export const navigationBackground = white
export const navigationTint = shipGray
export const secondaryButtonText = shipGray
export const secondaryButtonBackground = springWood
export const secondaryButtonDisabled = springWood10Dark
export const tertiaryButtonBackground = white
export const progressBackground = cararra
export const inputTextBorder = '#eaeaea'
export const loadingOverlayBackground = '#00000033'
export const inputTextErrorMessage = cinnarbar
export const modalOverlayBackground = '#00000066'
export const groupedListBackground = springWood
export const separator = lightGrey
export const activeItemBackground = springWood
export const primaryColor = blueRibbon
export const lightBackground = iceBlue
export const primaryButtonBackgroundDisabled = blueRibbon80Light
export const primaryButtonBackgroundHighlight = blueRibbon50Light
export const primaryButtonTextColor = white
export const coloredText = blueRibbon
export const quickPollProgress = anakiwa
