source "https://rubygems.org"

ruby '2.7.1'
gem 'fastlane', '>= 2.166.0'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)