export default {
  pap: require('@/assets/images/actionMap/pap-marker.png'),
  boitage: require('@/assets/images/actionMap/boitage-marker.png'),
  tractage: require('@/assets/images/actionMap/tractage-marker.png'),
  collage: require('@/assets/images/actionMap/collage-marker.png'),
  papActive: require('@/assets/images/actionMap/papActive-marker.png'),
  boitageActive: require('@/assets/images/actionMap/boitageActive-marker.png'),
  tractageActive: require('@/assets/images/actionMap/tractageActive-marker.png'),
  collageActive: require('@/assets/images/actionMap/collageActive-marker.png'),
  'pap-passed': require('@/assets/images/actionMap/pap-passed-marker.png'),
  'boitage-passed': require('@/assets/images/actionMap/boitage-passed-marker.png'),
  'tractage-passed': require('@/assets/images/actionMap/tractage-passed-marker.png'),
  'collage-passed': require('@/assets/images/actionMap/collage-passed-marker.png'),
  'papActive-passed': require('@/assets/images/actionMap/papActive-passed-marker.png'),
  'boitageActive-passed': require('@/assets/images/actionMap/boitageActive-passed-marker.png'),
  'tractageActive-passed': require('@/assets/images/actionMap/tractageActive-passed-marker.png'),
  'collageActive-passed': require('@/assets/images/actionMap/collageActive-passed-marker.png'),
  'pap-cancelled': require('@/assets/images/actionMap/pap-cancelled-marker.png'),
  'boitage-cancelled': require('@/assets/images/actionMap/boitage-cancelled-marker.png'),
  'tractage-cancelled': require('@/assets/images/actionMap/tractage-cancelled-marker.png'),
  'collage-cancelled': require('@/assets/images/actionMap/collage-cancelled-marker.png'),
  'papActive-cancelled': require('@/assets/images/actionMap/papActive-cancelled-marker.png'),
  'boitageActive-cancelled': require('@/assets/images/actionMap/boitageActive-cancelled-marker.png'),
  'tractageActive-cancelled': require('@/assets/images/actionMap/tractageActive-cancelled-marker.png'),
  'collageActive-cancelled': require('@/assets/images/actionMap/collageActive-cancelled-marker.png'),
} as const
