export const FEATURES = {
  ACTIONS: 'actions',
  ADHERENT_FORMATIONS: 'adherent_formations',
  COMMITTEE: 'committee',
  CONTACTS: 'contacts',
  CONTACTS_EXPORT: 'contacts_export',
  DASHBOARD: 'dashboard',
  DEPARTMENT_SITE: 'department_site',
  DESIGNATION: 'designation',
  DOCUMENTS: 'documents',
  ELECTED_REPRESENTATIVE: 'elected_representative',
  ELECTIONS: 'elections',
  EVENTS: 'events',
  FEATUREBASE: 'featurebase',
  GENERAL_MEETING_REPORTS: 'general_meeting_reports',
  MESSAGES: 'messages',
  MY_TEAM: 'my_team',
  NEWS: 'news',
  PAP: 'pap',
  PAP_V2: 'pap_v2',
  PHONING_CAMPAIGN: 'phoning_campaign',
  PROCURATIONS: 'procurations',
  RIPOSTES: 'ripostes',
  STATUTORY_MESSAGE: 'statutory_message',
  SURVEY: 'survey',
  TEAM: 'team',
  MOBILE_APP: 'mobile_app',
} as const

export const HIDDEN_FEATURES = [FEATURES.CONTACTS_EXPORT]

export const FEATURES_TRANSLATION = {
  [FEATURES.ACTIONS]: 'Actions',
  [FEATURES.ADHERENT_FORMATIONS]: 'Formations',
  [FEATURES.COMMITTEE]: 'Comités locaux',
  [FEATURES.CONTACTS]: 'Militants',
  [FEATURES.CONTACTS_EXPORT]: 'Militants (export)',
  [FEATURES.DASHBOARD]: "Vue d'ensemble",
  [FEATURES.DEPARTMENT_SITE]: 'Site départemental',
  [FEATURES.DESIGNATION]: 'Élections CL',
  [FEATURES.DOCUMENTS]: 'Documents',
  [FEATURES.ELECTED_REPRESENTATIVE]: 'Registre des élus',
  [FEATURES.ELECTIONS]: 'Historique élections',
  [FEATURES.EVENTS]: 'Événements',
  [FEATURES.GENERAL_MEETING_REPORTS]: "Centre d'archives",
  [FEATURES.MESSAGES]: 'Messagerie',
  [FEATURES.MY_TEAM]: 'Mon équipe',
  [FEATURES.NEWS]: 'Notifications',
  [FEATURES.PAP]: 'Porte à porte',
  [FEATURES.PAP_V2]: 'Porte à porte local',
  [FEATURES.PHONING_CAMPAIGN]: 'Phoning',
  [FEATURES.PROCURATIONS]: 'Procurations',
  [FEATURES.RIPOSTES]: 'Action numérique',
  [FEATURES.STATUTORY_MESSAGE]: 'Emails statutaires',
  [FEATURES.SURVEY]: 'Questionnaires',
  [FEATURES.TEAM]: 'Groupes',
  [FEATURES.MOBILE_APP]: 'App mobile',
  [FEATURES.FEATUREBASE]: "Module d'aide",
} as const

const FEATURES_GROUPS = {
  GLOBAL: 'global',
  COMMUNICATION: 'communication',
  TERRITOIRES: 'territoire',
  ELECTIONS: 'elections',
  STATUTAIRE: 'statutaire',
  OTHER: 'autre',
} as const

export const GROUPS_TRANSLATION = {
  [FEATURES_GROUPS.GLOBAL]: '',
  [FEATURES_GROUPS.COMMUNICATION]: 'Communication',
  [FEATURES_GROUPS.TERRITOIRES]: 'Territoire',
  [FEATURES_GROUPS.ELECTIONS]: 'Élections',
  [FEATURES_GROUPS.STATUTAIRE]: 'Statutaire',
  [FEATURES_GROUPS.OTHER]: 'Autre',
} as const

export const FEATURES_STRUCT = {
  [FEATURES_GROUPS.GLOBAL]: [FEATURES.DASHBOARD, FEATURES.MY_TEAM, FEATURES.FEATUREBASE],
  [FEATURES_GROUPS.COMMUNICATION]: [FEATURES.MESSAGES, FEATURES.NEWS, FEATURES.DEPARTMENT_SITE, FEATURES.MOBILE_APP],
  [FEATURES_GROUPS.TERRITOIRES]: [
    FEATURES.CONTACTS,
    FEATURES.EVENTS,
    FEATURES.ACTIONS,
    FEATURES.ADHERENT_FORMATIONS,
    FEATURES.SURVEY,
    FEATURES.PHONING_CAMPAIGN,
    FEATURES.TEAM,
  ],
  [FEATURES_GROUPS.ELECTIONS]: [FEATURES.ELECTIONS, FEATURES.PROCURATIONS, FEATURES.PAP, FEATURES.PAP_V2, FEATURES.RIPOSTES],
  [FEATURES_GROUPS.STATUTAIRE]: [
    FEATURES.COMMITTEE,
    FEATURES.STATUTORY_MESSAGE,
    FEATURES.DESIGNATION,
    FEATURES.ELECTED_REPRESENTATIVE,
    FEATURES.DOCUMENTS,
    FEATURES.GENERAL_MEETING_REPORTS,
  ],
} as const
