require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
inhibit_all_warnings!

target 'JeMarche' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'JeMarcheTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  
  # See https://stackoverflow.com/questions/66019068/event2-event-config-h-file-not-found for issue on Xcode 12.5
  use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
