require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
inhibit_all_warnings!

target 'JeMarche' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'JeMarcheTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end