export const API_BASE_URL = process.env.EXPO_PUBLIC_API_BASE_URL
export const OAUTH_CLIENT_ID = process.env.EXPO_PUBLIC_OAUTH_CLIENT_ID
export const OAUTH_CLIENT_SECRET = process.env.EXPO_PUBLIC_OAUTH_CLIENT_SECRET
export const ENVIRONMENT = process.env.EXPO_PUBLIC_ENVIRONMENT
export const SENTRY_DSN = process.env.EXPO_PUBLIC_SENTRY_DSN
export const IOS_GOOGLE_API_KEY = process.env.EXPO_PUBLIC_IOS_GOOGLE_API_KEY
export const ANDROID_GOOGLE_API_KEY = process.env.EXPO_PUBLIC_ANDROID_GOOGLE_API_KEY
export const BUNDLE_ID = process.env.EXPO_PUBLIC_BUNDLE_ID



