name: Release branches
on:
  push:
    branches:
      - 'develop'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build-web:
    runs-on: ubuntu-latest
    environment: staging
    env:
      EXPO_PUBLIC_API_BASE_URL: ${{secrets.EXPO_PUBLIC_API_BASE_URL}}
      EXPO_PUBLIC_OAUTH_BASE_URL: ${{secrets.EXPO_PUBLIC_OAUTH_BASE_URL}}
      EXPO_PUBLIC_OAUTH_CLIENT_ID: ${{secrets.EXPO_PUBLIC_OAUTH_CLIENT_ID}}
      EXPO_PUBLIC_OAUTH_CLIENT_SECRET: ${{secrets.EXPO_PUBLIC_OAUTH_CLIENT_SECRET}}
      EXPO_PUBLIC_SENTRY_DSN: ${{secrets.EXPO_PUBLIC_SENTRY_DSN}}
      EXPO_PUBLIC_IOS_GOOGLE_API_KEY: ${{secrets.EXPO_PUBLIC_IOS_GOOGLE_API_KEY}}
      EXPO_PUBLIC_ANDROID_GOOGLE_API_KEY: ${{secrets.EXPO_PUBLIC_ANDROID_GOOGLE_API_KEY}}
      EXPO_PUBLIC_FB_API_KEY: ${{secrets.EXPO_PUBLIC_FB_API_KEY}}
      EXPO_PUBLIC_FB_PROJECT_ID: ${{secrets.EXPO_PUBLIC_FB_PROJECT_ID}}
      EXPO_PUBLIC_FB_SENDER_ID: ${{secrets.EXPO_PUBLIC_FB_SENDER_ID}}
      EXPO_PUBLIC_FB_APP_ID: ${{secrets.EXPO_PUBLIC_FB_APP_ID}}
      EXPO_PUBLIC_FB_MEASUREMENT_ID: ${{secrets.EXPO_PUBLIC_FB_MEASUREMENT_ID}}
      EXPO_PUBLIC_ENVIRONMENT: ${{secrets.EXPO_PUBLIC_ENVIRONMENT}}
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/dependencies
      - name: ⚙️ Compile web worker
        run: yarn vite build --config vite.worker.config.js
      - name: ⚙️ Compile web assets
        uses: ./.github/actions/build-web
      - name: ↗️ Upload web assets
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      - name: ↗️ Upload tamagui cache
        uses: actions/upload-artifact@v4
        with:
          name: tamagui
          path: .tamagui

  upload-staging-develop-web:
    runs-on: ubuntu-latest
    needs: build-web
    environment: staging
    env:
      EXPO_PUBLIC_FB_PROJECT_ID: ${{vars.FIREBASE_PROJECT}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        name: ⬇️ Download web artifacts
      - uses: ./.github/actions/setup-base
      - uses: ./.github/actions/dependencies
      - uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          credentials_json: ${{ secrets.GCP_SA_KEY_FIREBASE_DEPLOYER }}
      - uses: ./.github/actions/deploy-firebase-live
        id: deploy
        name: 🚀 Send to firebase LIVE hosting
      - name: 📢 Announce deployment
        env:
          URL: ${{steps.deploy.outputs.url}}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: node ./.github/scripts/announce.js
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        name: ⬇️ Download web artifacts
      - uses: ./.github/actions/setup-base
      - name: 🧙🏻‍️Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: yarn
          token: ${{ secrets.EXPO_TOKEN }}
      - uses: ./.github/actions/dependencies
      - name: ⚙️ Compile android
        run: eas build --platform android --profile=staging --no-wait
