name: CI iOS
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./ios
          bundler: 'Gemfile.lock'
          bundler-cache: true

      - name: Use Node.js 21
        uses: actions/setup-node@v1
        with:
          node-version: '21.1.0'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Set up node dependencies
        run: yarn install

      - name: Prepare env
        env:
          RN_B64_ENV_STAGING: ${{ secrets.RN_B64_ENV_STAGING }}
          RN_B64_ENV_PRODUCTION: ${{ secrets.RN_B64_ENV_PRODUCTION }}
          IOS_B64_FASTLANE_ENV_DEFAULT: ${{ secrets.IOS_B64_FASTLANE_ENV_DEFAULT }}
          IOS_B64_FASTLANE_ENV_STAGING: ${{ secrets.IOS_B64_FASTLANE_ENV_STAGING }}
          IOS_B64_FASTLANE_ENV_PRODUCTION: ${{ secrets.IOS_B64_FASTLANE_ENV_PRODUCTION }}
          IOS_B64_FASTLANE_ENV_DISTRIBUTION: ${{ secrets.IOS_B64_FASTLANE_ENV_DISTRIBUTION }}
          IOS_B64_FIREBASE_PLIST_STAGING: ${{ secrets.IOS_B64_FIREBASE_PLIST_STAGING }}
          IOS_B64_FIREBASE_PLIST_PRODUCTION: ${{ secrets.IOS_B64_FIREBASE_PLIST_PRODUCTION }}
        run: ./cli.js prepare staging

      - name: Pods cache
        uses: actions/cache@v1
        with:
          path: ./ios/Pods
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('ios/**/Podfile.lock') }}

      - name: Pod install
        working-directory: ./ios
        run: |
          if [ ! -d "Pods" ]; then
            bundle exec pod install || bundle exec pod install --repo-update
          fi

      - name: Build and test
        working-directory: ./ios
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
        run: bundle exec fastlane build
