name: Release branches
on:
  push:
    branches:
      - 'ci/*'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

env:
  EAS_BUILD_PROFILE: development

jobs:
  build-android:
    runs-on: ubuntu-latest
    environment: staging
    env:
      EXPO_PUBLIC_API_BASE_URL: ${{secrets.EXPO_PUBLIC_API_BASE_URL}}
      EXPO_PUBLIC_OAUTH_BASE_URL: ${{secrets.EXPO_PUBLIC_OAUTH_BASE_URL}}
      EXPO_PUBLIC_OAUTH_CLIENT_ID: ${{secrets.EXPO_PUBLIC_OAUTH_CLIENT_ID}}
      EXPO_PUBLIC_OAUTH_CLIENT_SECRET: ${{secrets.EXPO_PUBLIC_OAUTH_CLIENT_SECRET}}
      EXPO_PUBLIC_SENTRY_DSN: ${{secrets.EXPO_PUBLIC_SENTRY_DSN}}
      EXPO_PUBLIC_IOS_GOOGLE_API_KEY: ${{secrets.EXPO_PUBLIC_IOS_GOOGLE_API_KEY}}
      EXPO_PUBLIC_ANDROID_GOOGLE_API_KEY: ${{secrets.EXPO_PUBLIC_ANDROID_GOOGLE_API_KEY}}
      EXPO_PUBLIC_FB_API_KEY: ${{secrets.EXPO_PUBLIC_FB_API_KEY}}
      EXPO_PUBLIC_FB_PROJECT_ID: ${{secrets.EXPO_PUBLIC_FB_PROJECT_ID}}
      EXPO_PUBLIC_FB_SENDER_ID: ${{secrets.EXPO_PUBLIC_FB_SENDER_ID}}
      EXPO_PUBLIC_FB_APP_ID: ${{secrets.EXPO_PUBLIC_FB_APP_ID}}
      EXPO_PUBLIC_FB_MEASUREMENT_ID: ${{secrets.EXPO_PUBLIC_FB_MEASUREMENT_ID}}
      EXPO_PUBLIC_ENVIRONMENT: ${{secrets.EXPO_PUBLIC_ENVIRONMENT}}
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4
      - name: 🛠️ Prepare node env
        uses: ./.github/actions/setup-base
      - name: 📦 Fetch dependencies
        uses: ./.github/actions/dependencies
      - name: ⚙️ Compile web assets (needed for tamagui assets bug)
        uses: ./.github/actions/build-web
      - name: 🧙🏻‍️Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: ⚙️ Compile android
        run: eas build --platform android --profile=staging --no-wait
