name: Deploy on firebase
description: Deploy on firebase hosting

outputs:
  url:
    description: "Deployment URL"
    value: ${{steps.extractor.outputs.url}}"

runs:
  using: composite
  steps:
    - name: 📦 Deploy on firebase
      shell: bash
      run: npx firebase deploy --only hosting --project "${EXPO_PUBLIC_FB_PROJECT_ID}"
    - name: Extract deployed URL
      id: extractor
      shell: bash
      run: cat output.txt | grep "Hosting URL" | awk -F 'https://' '{print "https://" $2}' | awk '{print "url="$1}' >> $GITHUB_OUTPUT
